Added actions state management
php-etl/console-state pull request #1
Opened 2023-03-07 16:05 UTC by sebprt

2023-04-18 15:52 UTC, gplanchat approved these changes

2023-04-19 08:13 UTC, gplanchat requested changes

2023-04-19 08:13 UTC, gplanchat commented on composer.json
> +            "dev-main": "0.3.x-dev"
```suggestion
            "dev-main": "0.2.x-dev"
```

2023-04-19 08:27 UTC, sebprt commented on composer.json
> +            "dev-main": "0.3.x-dev"
J'ai supprimé le commit

2023-04-19 08:43 UTC, merged